spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hello
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
